In [1]:
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from polypesto.core import create_sim_conditions, simulate_problem
from polypesto.core.pypesto import calculate_cis, create_ensemble, predict_with_ensemble
from polypesto.examples.base import output_dirs

# Model specific imports
from polypesto.models.binary import BinaryIrreversible
from polypesto.models.binary.utils import create_ensemble_pred_problem
from polypesto.vis import plot_ensemble_predictions

%load_ext autoreload
%autoreload 2

In [ ]:
OUTPUT_DIR = Path(
    "/Users/devoncallan/Documents/GitHub/PolyPESTO/polypesto/examples/output/simulated"
)
model = BinaryIrreversible(observables=["xA", "FA", "fA"], obs_noise=0.01)

# Define true parameters and simulation conditions
true_params = {"rA": 2.0, "rB": 1.0}
sim_conds = create_sim_conditions(
    true_params=true_params,
    conds=dict(
        A0=[0.70, 0.50],
        B0=[0.30, 0.50],
    ),
    t_evals=np.arange(0.05, 0.61, 0.05),
    meas_noise=0.01,
)

# Simulate problem and create parameter estimation problem
problem = simulate_problem(
    prob_dir=OUTPUT_DIR,
    model=model,
    conds=sim_conds,
    overwrite=True,
)

# Run parameter estimation (optimization + sampling)
result = problem.run_parameter_estimation(
    config=dict(
        optimize=dict(n_starts=50, method="Nelder-Mead"),
        sample=dict(n_samples=10000, n_chains=3),
    ),
    overwrite=True,
)

Engine will use up to 8 processes (= CPU count).

==== Running optimization ====

100%|██████████| 50/50 [00:06<00:00,  7.44it/s]
Initializing betas with "near-exponential decay".

==== Running sampling ====

100%|██████████| 10000/10000 [00:09<00:00, 1067.47it/s]
Elapsed time: 9.211473

In [ ]:
# Predict using parameter ensemble from sampling
ens_prob = create_ensemble_pred_problem(problem.paths.ensemble_dir, model)
# ens, ens_pred = problem.ensemble_prediction(ens_prob)

Engine will use up to 8 processes (= CPU count).

==== Running ensemble predictions ====

100%|██████████| 8/8 [00:24<00:00,  3.07s/it]

Error saving plot to /Users/devoncallan/Documents/GitHub/PolyPESTO/polypesto/examples/output/simulated/figures/ensemble_predictions.png: EnsemblePrediction.compute_summary.<locals>._compute_summary() missing 1 required positional argument: 'weights'

In [ ]:
ens_pred.prediction_results[0].conditions[0].output_sensi

In [3]:
import seaborn as sns
import pandas as pd


def highlight_value_above_threshold(x, threshold=1):
    return ["color: darkorange" if xi > threshold else None for xi in x]


def highlight_gradient_check(gc: pd.DataFrame):
    return (
        gc.style.apply(
            highlight_value_above_threshold,
            subset=["fd_err"],
        )
        .background_gradient(
            cmap=sns.light_palette("purple", as_cmap=True),
            subset=["abs_err"],
        )
        .background_gradient(
            cmap=sns.light_palette("red", as_cmap=True),
            subset=["rel_err"],
        )
        .background_gradient(
            cmap=sns.color_palette("viridis", as_cmap=True),
            subset=["eps"],
        )
    )


parameter_vector = problem.pypesto_problem.x_guesses[0]
gc = problem.pypesto_problem.objective.check_grad_multi_eps(
    x=parameter_vector,
    verbosity=0,
    label="rel_err",  # default
)

highlight_gradient_check(gc)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [10]:
problem.pypesto_problem.get_startpoints(n_starts=100)

array([[-0.10130563, -2.0105881 ],
       [ 1.70069211, -2.61302623],
       [-2.85642803, -2.20725953],
       [-0.43621493,  0.49089584],
       [-2.85945259,  0.64265197],
       [ 0.32607623, -2.38632237],
       [ 0.63704192, -1.48334836],
       [-0.37889808,  1.93517829],
       [ 0.35230584, -2.36322494],
       [ 0.62780243, -1.85579196],
       [-1.19269211, -0.81544917],
       [ 1.45542406, -2.89091842],
       [ 0.08655632, -0.26566506],
       [-2.79489598, -2.24636906],
       [ 1.58870891,  0.41983201],
       [ 1.40361058, -2.46903307],
       [-2.48359507, -0.07772898],
       [-2.26598139, -1.60305127],
       [ 1.6322892 , -1.62883944],
       [ 0.95836877,  1.31289687],
       [-1.97806546,  0.55380577],
       [ 0.14788463, -2.77668483],
       [-0.18359668, -2.00034351],
       [-1.77531441,  1.81606631],
       [-2.64367288, -0.27015994],
       [-1.6668413 , -2.78284478],
       [ 0.3425954 , -0.19187724],
       [ 0.09984154,  1.76619898],
       [-0.3501439 , -1.15333555],
       [ 1.95973535,  1.25070125],
       [ 0.54291047, -0.73384798],
       [ 0.65054965,  0.09674556],
       [-0.79599606,  0.22435332],
       [-0.65779449, -0.91478722],
       [-0.908818  , -1.32403468],
       [-1.67255438,  0.90991843],
       [-1.28468818,  0.38152763],
       [-1.80649792,  1.53851641],
       [-1.29511224, -0.26064898],
       [-1.44708876,  0.39778237],
       [-1.87793823, -2.12321325],
       [ 0.20740654, -0.01520763],
       [-0.41486605, -1.74750746],
       [ 1.89720436, -1.32870048],
       [ 0.34029407, -0.91085989],
       [-2.9557197 , -2.78848343],
       [-2.24299738, -1.64781353],
       [ 1.8413332 , -2.87130006],
       [-2.82082901, -2.89855763],
       [ 1.82816326,  0.20263254],
       [-0.79331026,  1.4668897 ],
       [-2.75632352, -0.09168075],
       [-2.37606276,  1.06922044],
       [ 1.74523582, -0.36406664],
       [-0.9775094 ,  1.05683062],
       [ 1.49389763,  0.99454807],
       [-0.69938918, -2.74260069],
       [-2.35994589, -2.15728789],
       [-1.08404764, -0.30064703],
       [ 1.62349041, -1.97634916],
       [ 0.57924729,  0.53152265],
       [ 1.92539785,  1.15538398],
       [-1.3045842 ,  0.62677919],
       [-1.09478121, -1.40695642],
       [-1.3608209 , -2.27526276],
       [ 0.67288301, -2.73244057],
       [-0.14866352, -0.20753539],
       [-2.44722209, -2.6879061 ],
       [ 0.43030309,  1.32418178],
       [-1.564023  ,  1.49709059],
       [ 1.46664521, -2.86713036],
       [-2.74400418, -1.55180528],
       [-2.5484281 ,  0.51482541],
       [ 1.04395545,  1.27225367],
       [ 0.71242055, -1.15955627],
       [-1.2974637 ,  0.91494264],
       [ 0.78291328, -0.22174908],
       [ 0.8219453 ,  1.5224416 ],
       [ 1.4594986 , -2.76104952],
       [-1.50897733,  0.39183787],
       [ 1.01440651,  0.08575603],
       [-1.59428584, -2.29843752],
       [ 1.55948494, -1.43064965],
       [-1.95200217,  0.44128946],
       [-1.65553808,  0.6071003 ],
       [-0.12862456,  0.12358209],
       [ 1.71545268, -0.28849023],
       [-1.69103001, -0.34518325],
       [ 0.40679306,  0.40071538],
       [-0.19291141, -2.7780598 ],
       [-0.75451086,  1.45441729],
       [ 1.09165033,  0.45572419],
       [-1.36474401,  1.44953212],
       [ 0.19487578,  1.16047793],
       [ 1.83739912,  1.71029606],
       [-1.56270703, -2.82680498],
       [-0.01197374,  0.903122  ],
       [ 0.73966753, -1.55918141],
       [-0.77535688,  1.3210545 ],
       [ 1.79531044, -2.95660207]])

In [12]:
startpoints = problem.pypesto_problem.get_startpoints(n_starts=100)
problem.pypesto_problem.objective.check_grad(
    x=startpoints[0],
    eps=1e-5,  # default
    verbosity=0,
)

,grad,fd_f,fd_b,fd_c,fd_err,abs_err,rel_err
rA,-6641.573818,-8220.991681,-5074.098934,-6647.545308,3146.892747,5.971490,0.000898
rB,36.183831,-1537.908193,1610.157004,36.124405,3148.065197,0.059425,0.001645

In [14]:
parameter_vector = problem.pypesto_problem.get_reduced_vector(startpoints[0])
problem.pypesto_problem.objective.check_grad(
    x=parameter_vector,
    eps=1e-6,
    verbosity=0,
)

,grad,fd_f,fd_b,fd_c,fd_err,abs_err,rel_err
rA,-6641.573818,-22387.695438,9092.841766,-6647.426836,31480.537205,5.853018,0.000880
rB,36.183831,-15704.203787,15776.455972,36.126092,31480.659758,0.057738,0.001598

In [15]:
gc = problem.pypesto_problem.objective.check_grad_multi_eps(
    x=parameter_vector,
    verbosity=0,
    label="rel_err",  # default
)
highlight_gradient_check(gc)

In [ ]:
from pypesto import C

max_size = np.inf
x_vectors = []
x_names = [result.problem.x_names[i] for i in result.problem.x_free_indices]
abs_cutoff = np.inf
for start in result.optimize_result.list:

    if (
        start["fval"] <= abs_cutoff
        and len(x_vectors) < max_size
        # 'x' can be None if optimization failed at the startpoint
        and start["x"] is not None
    ):
        x_vectors.append(start["x"][result.problem.x_free_indices])
x_vectors = np.stack(x_vectors, axis=1)
print(x_vectors.shape)

In [ ]:
print(result.sample_result.trace_x[0, 0:, :].shape)

In [ ]:
from pypesto.ensemble.ensemble import calculate_hpd

print(result.sample_result.trace_x[0].shape)
print(calculate_hpd(result).shape)

In [ ]:
result.sample_result.trace_x[0][slice(None, None, 10)].shape

In [ ]:
# Predict using parameter ensemble from sampling
ens_prob = create_ensemble_pred_problem(problem.paths.ensemble_dir, model)
ens, ens_pred = problem.ensemble_prediction(ens_prob)

In [ ]:
ens_pred.condense_to_arrays()
ens_pred.prediction_arrays["output"].shape

In [ ]:
len(np.arange(0.01, 0.9, 0.01))

In [ ]:
ens_pred.condense_to_arrays()
ens_pred.prediction_arrays["output"].shape

In [ ]:
len(ens_pred.prediction_results)

In [ ]:
all_t = [cond.timepoints for cond in ens_pred.prediction_results[0].conditions]
sum(len(t) for t in all_t)

In [ ]:
# ens_pred.condense_to_arrays()
from pypesto.ensemble.util import get_prediction_dataset

# get_prediction_dataset(ens_pred)[:, 0, :]
get_prediction_dataset(ens_pred)

In [ ]:
ens.x_vectors

In [ ]:
ens_pred.prediction_arrays["output"]

In [ ]:
ens.check_identifiability()

In [ ]:
ens.compute_summary(percentiles_list=(5, 25, 75, 95))

In [ ]:
ens.compute_summary(percentiles_list=(5, 25, 75, 95))

In [ ]:
calculate_cis(result, ci_level=0.95)

In [ ]:
from pypesto.ensemble import (
    get_covariance_matrix_parameters,
    get_covariance_matrix_predictions,
)

get_covariance_matrix_parameters(ens)

from pypesto.visualize import parameters_correlation_matrix

In [ ]:
np.cov(ens.x_vectors)

In [ ]:
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(8, 6))
# plt.imshow(get_covariance_matrix_parameters(ens))
plt.imshow(np.corrcoef(ens.x_vectors))
plt.colorbar()
# ax.add_image(get_covariance_matrix_parameters(ens))

In [ ]:
np.corrcoef(ens.x_vectors)

In [ ]:
get_covariance_matrix_predictions(ens_pred)

In [ ]:
get_covariance_matrix_parameters(ens)

In [ ]:
from pypesto.visualize import ensemble_identifiability

ensemble_identifiability(ens)

In [ ]:
get_covariance_matrix_predictions(ens_pred, prediction_index=0)

In [ ]:
ens.x_vectors

In [ ]:
ens_pred.compute_summary(percentiles_list=(5, 25, 75, 95))

In [ ]:
ens_pred.prediction_arrays["output"]

In [ ]:
ens_pred.compute_chi2(problem.pypesto_problem.objective)